### ISSUE TITLE
v3.0.11 and Deferred Static Generation with GatsbyJs

### ISSUE THREAD

**Issue by jorge-mattress** [datocms/gatsby-source-datocms#187] opened 2022-01-25 12:29 UTC
I'm using gatsby v4 and a flag `defer = true` on certain pages with the `createPage` function inside `gatsby-node.js`

And the returned data from the dato-cms-source plugin contains certain items with empty or null values.

A sample of the returned data looks like this:
`{
    "promotions": [],
    "brand": null,
    "name": "Ecosa",
}`

You can see a test website here with the defer flag set to true: https://nzfeaturedsg.gatsbyjs.io/comparer/ecosa-mattress-vs-emma-original-mattress-vs-napp-mattress-vs-peacelily-mattress

And defer flag set to false: https://nzfeaturedsg.gatsbyjs.io/comparer/ecosa-mattress-vs-emma-original-mattress

Many thanks in advance for any feedback.

**Comment by stefanoverna** [comment] 2022-01-27 07:48
Hi! Any chance we can take a look at the code?

**Comment by jorge-mattress** [comment] 2022-01-27 13:10
Oh forgot to provide more details, please check the gatsny-node.js here:
https://gist.github.com/jorge-mattress/4248c423e7b5e76927a01160a7e238a0

And the template that renders the pages
https://gist.github.com/jorge-mattress/bed4a39c6b8f9acd5d43b440250fe39f

The bits that matter the more for us inside the graphql are "promotions" and "brand" and both return null or empty array, hope this helps:
`promotions {
                    startDate
                    endDate
                    description
                    affiliateLinkCta
                    altTitle
                    affiliateLinkPromotion {
                        affiliateLink
                        shortenedAffiliateLink
                    }
                }
                brand {
                    meta {
                        updatedAt
                    }
                    brandName
                    discountFlat
                    discountPercentage
                    promotions {
                        startDate
                        endDate
                        description
                        affiliateLinkCta
                        altTitle
                        affiliateLinkPromotion {
                            affiliateLink
                            shortenedAffiliateLink
                        }
                    }
                }`
                
               Please let me know if you need more info, many thanks in advance!

**Comment by stefanoverna** [comment] 2022-01-28 11:32
Yes, please can you send us the complete Gatsby project + the name of your DatoCMS project at support@datocms.com?
If the Gatsby project is on Github, you can share it with me!

Thanks

**Comment by jorge-mattress** [comment] 2022-01-28 12:42
Thanks! already sent the info to the provided email

**Comment by stefanoverna** [comment] 2022-01-28 14:50
@jorge-mattress I've been able to reproduce the issue, thank you. 

Honestly, I haven't the slightest idea why it does that. I assume it's a bug in Gatsby, as we're we're simply generating the nodes.. and everything else is in Gatsby's hands. So if the nodes we generate work in one context, they should also work in other.

I've used our internal Slack channel with Gatsby to ask for help, hope to give you some updates soon 😢

**Comment by jorge-mattress** [comment] 2022-01-31 08:48
Thanks a lot for your help @stefanoverna, I hope we can solve this issue soon.

**Comment by pieh** [comment] 2022-02-17 14:04
We've been looking at differences when running queries in develop vs in engine and in internals of `link` resolver we saw differences in both.

In particular in https://github.com/datocms/gatsby-source-datocms/blob/741119e9d9250bffdffdded07b335de106eb53ad/src/hooks/sourceNodes/createTypes/item/fields/link.js#L28

In engines we get `undefined` vs A proxy in `gatsby develop`. We also see that `entitiesRepo` seems much smaller in engines - it lacks some keys at very least

Left is engines (dsg/ssr case), right is gatsby develop:
![Screenshot 2022-02-17 at 14 58 45](https://user-images.githubusercontent.com/419821/154497217-76695976-f9d6-4cc0-9f35-7dd74e43e27b.png)

Because left is returning `undefined` I assume that's why links resolve to empty array. Does `entitiesRepo` need to be "populated" somehow?

**Comment by dw-srohrlack** [comment] 2022-02-17 16:44
fyi: we've seen this behaviour using gatsby-source-datocms 3.0.8

running the latest versions of gatsby (4.7.2) and gatsby-source-datocms (3.0.15) doesn't seem to solve the issue

**Comment by stefanoverna** [comment] 2022-03-31 13:57
Hey @pieh, thanks for investigating. 

Please @jorge-mattress && @dw-srohrlack try gatsby-source-datocms v3.0.18-0 and let us know if it fixes the issue!

**Comment by jorge-mattress** [comment] 2022-03-31 15:21
Excellent news!
Going to post the results in short.
But thanks beforehand for all the help!

**Comment by matjack1** [comment] 2022-04-01 14:47
hey @jorge-mattress and @dw-srohrlack we have a preview version v3.0.18-0 that should fix this issue, can you please upgrade and let us know? Thanks!

**Comment by matjack1** [comment] 2022-04-01 15:06
excellent! Thank you very much for the feedback!

Nothing else to do on your end, we'll soon release the version to everyone, but you shouldn't need to upgrade. Thank you again!

**Comment by dw-srohrlack** [comment] 2022-04-06 13:23
I can confirm that it's working marvelous 👌

**Comment by stefanoverna** [comment] 2022-04-06 13:24
Released as 3.0.18! Thanks everyone!

**Closed by stefanoverna** 2022-04-06 13:24 UTC
