### ISSUE TITLE
Is there a way to enable Strict Mode?

### ISSUE THREAD

**Issue by dante-blitz** [datocms/gatsby-source-datocms#198] opened 2022-07-21 12:11 UTC
Hi there,

I'm recently started working with Gatsby's GraphQL Typegen and types are being generated as expected. However typescript is givieng null error onrequired fields. For example...

```
Type 'string | null | undefined' is not assignable to type 'string'.
Type 'undefined' is not assignable to type 'string'.ts(2322)
```

I've read your [Strict Mode](https://www.datocms.com/blog/introducing-strict-mode-for-graphql-cda-get-the-best-typescript-dx) announcement post and your [Strict Mode](https://www.datocms.com/docs/content-delivery-api/api-endpoints#strict-mode-for-non-nullable-graphql-types) docs, but I'm not sure how to enable Strict Mode with this source plugin.

Any guidance is very highly appreciated.

**Comment by matjack1** [comment] 2022-08-30 15:56
@dante-blitz unfortunately the strict mode is for our GraphQL API. Gatsby is using our REST API to fetch data and then exposes it through their internal GraphQL API. So we would need to rewrite the source plugin using our latest JS client that is in Typescript: https://github.com/datocms/js-rest-api-clients

I'm closing this as it's a duplicate of: https://github.com/datocms/gatsby-source-datocms/issues/126

**Closed by matjack1** 2022-08-30 15:56 UTC
