### ISSUE TITLE
createNodeField does not create a field

### ISSUE THREAD

**Issue by stzonis** [datocms/gatsby-source-datocms#92] opened 2020-01-19 11:56 UTC
Hi,
I am trying to add a field to an existing DatoCMS node but it doesn't work.

I have added this code in the file `gatsby-node.js`:

```
exports.onCreateNode = ({ node, actions }) => {
  const { createNodeField } = actions
  if (node.internal.type === "DatoCmsPerson") {
    // console.log(node) // the node extists
    createNodeField({
      node,
      name: "hello",
      value: "hello!!!",
    })
  }
}
```

Any ideas why I don't see the field in GraphiQL?

**Comment by matjack1** [comment] 2020-01-20 10:48
hey @stzonis 

The only thing that I've found that you can try is to change `onCreateNode` to this:

```
exports.onCreateNode = ({ node, getNode, actions }) => {
  const { createNodeField } = actions
}
```
?

**Comment by stzonis** [comment] 2020-01-20 14:46
hey @matjack1

It still doesn't work with your change...

Many thanks for your help!

**Comment by matjack1** [comment] 2020-01-21 09:54
I'm going to close this as I think it's more related with Gatsby rather than with our sourc plugin, but if you instead think it has to do with Dato feel free to comment again and provide more info on this. Sorry I cannot help you more here.

**Comment by stzonis** [comment] 2020-01-21 20:47
Ok!

**Comment by dbismut** [comment] 2020-02-22 15:23
@matjack1 I believe this is definitely linked to this plugin, not Gatsby.

v2.1 seems to break `onCreateNode` or `createNodeField`. It worked fine with 2.0.0. This is I believe critical.

**Comment by stefanoverna** [comment] 2020-02-24 12:44
Reopening!

**Comment by winstonma** [comment] 2020-03-14 12:52
Yeah I got this problem too. I tried to download the image from remote and served locally. Here is my code.

```
exports.onCreateNode = async ({
  node,
  actions,
  store,
  cache,
  createNodeId
}) => {
  if (node.internal.type === `DatoCmsVideoItem`) {
    const imageURL = node.videoId;

    let fileNode = await createRemoteFileNode({
      url: imageURL, // string that points to the URL of the image
      parentNodeId: node.id, // id of the parent node of the fileNode you are going to create
      createNode, // helper function in gatsby-node to generate the node
      createNodeId, // helper function in gatsby-node to generate the node id
      cache, // Gatsby's cache
      store // Gatsby's redux store
    });

    createNodeField({
      node,
      name: `featuredImg___NODE`,
      value: fileNode.id,
    });
  }
};
```

I found that the remote image (file) is created, it also has the `parent.id` of the original `DatoCmsVideoItem`. However I have no luck accessing the field `featuredImg`. I am not sure but it seems the `createNodeField` doesn't work on the node related to DatoCMS.

**Comment by matjack1** [comment] 2020-03-19 14:41
hey @winstonma I've tried to reproduce your issue and yes I cannot access the `featuredImg` in GraphiQL, but if I do something like this:

```
exports.onPostBootstrap = ({ getNodes }) => {
  const nodes = getNodes();

  nodes.forEach(node => {
    if (node.internal.type === `DatoCmsVideoItem`) {
      console.log(node.fields.featuredImg);
    }
  })
}
```

it works just fine (apart that there are some issues in your example, which I've simplified to add a plain field).

I'm going to comment also on the issue on the Gatsby repo. Let me know if you have any updates.

**Comment by winstonma** [comment] 2020-03-20 01:17
@matjack1 You are totally correct.

As long as the bug is confirmed and the test case is repeatable, then it should be easy to tackle the problem.

**Comment by Js-Brecht** [comment] 2020-03-20 16:18
@matjack1 responding to your question on the Gatsby thread:

> should we remove that? We stop inferring because we had some compatibility issues and it was going to be deprecated in the future?
> 
> What's the recommended behaviour there? Thank you!

Can you point me to where it says type inferring is deprecated?  I tried finding a blog post, issue log, and even scanned the code base, but couldn't find anything that said `@infer` or `@dontinfer` was going away.

I see that the `noDefaultResolvers` argument of the `@infer` directive is deprecated [[ref](https://www.gatsbyjs.org/blog/2019-05-17-improvements-to-schema-customization/)].  They want you to add resolvers **explicitly** now, so that Gatsby doesn't have to determine what resolvers to attach to arbitrary field types... which makes sense to me.  I never was a fan of having resolvers magically appear on fields; makes things easier to track when it's explicit, for one, and it's more efficient.

Type inferring is such an integral part of the schema generation, I'm not sure how they would remove it without causing an astronomical amount of work for every single plugin, and for every single end user.

**Comment by matjack1** [comment] 2020-03-20 17:28
@Js-Brecht you are right, sorry I was confused myself. Thank you so much for clarifying and pointing me in the right direction.

I think I've found a solution.

@winstonma I think you should use `createResolvers` as explained here: https://www.gatsbyjs.org/docs/schema-customization#extending-third-party-types

I've done this simple example that works for me:

```
exports.createResolvers = ({
  createResolvers
}) => {
  createResolvers({
    DatoCmsVideoItem: {
      featuredImg: {
        type: `String`,
        resolve(source, args, context, info) {
          return 'test';
        },
      },
    },
  })
}
```

Can you please confirm that works for you too?

@Js-Brecht does that make sense?

**Comment by Js-Brecht** [comment] 2020-03-20 17:38
@matjack1 I think that would be the ideal method in this context.

To use @winstonma's example, you could also do something like this, since the `resolve()` function supports promises:
```js
exports.createResolvers = ({
  createResolvers,
  store,
  cache,
  createNode,
  createNodeId,
  reporter
}) => {
  createResolvers({
    DatoCmsVideoItem: {
      featuredImg: {
        type: `File`,
        resolve(source, args, context, info) {
          return createRemoteFileNode({
            url: source.videoId,
            store,
            cache,
            createNode,
            createNodeId,
            reporter
          });
        },
      },
    },
  })
}
```

---

Quick question: how was type inferring breaking compatibility?  Is that something specific to DatoCms data structure maybe?

**Comment by winstonma** [comment] 2020-03-20 19:15
@Js-Brecht I need to modify the top part of your code slightly. Here is the modifiaction.

```
exports.createResolvers = ({
  actions,
  cache,
  createNodeId,
  createResolvers,
  store,
  reporter
}) => {
  const { createNode } = actions;
  ...
```

Thanks again

**Comment by Js-Brecht** [comment] 2020-03-20 19:17
> @Js-Brecht I need to modify the top part of your code slightly. Here is the modifiaction.

You're totally right.  I forget these things sometimes when I'm just winging it.  Thanks for the correction!

**Comment by winstonma** [comment] 2020-03-20 19:26
@matjack1 Thanks for this.

Just wonder if adding node fields using `onCreateNode`  would not be the official way in the future release?

**Comment by matjack1** [comment] 2020-03-23 08:37
Thank you very much @Js-Brecht for participating in this issue, very appreciated!

@winstonma from Gatsby's documentation I think that `createResolvers` is the preferred way to handle this now and in the future as you'll always need to modify a schema set by a plugin.

I'll add some documentation about this in the readme.

I'm going to close this for now as I think we've found a solution, but please comment more if necessary.

**Closed by matjack1** 2020-03-23 08:37 UTC
Labels: bug

**Comment by winstonma** [comment] 2020-09-27 12:49
Hi @matjack1 I guess I saw the problem lately. I just tried to build the web site recently and saw the problem, I need to make the modification (The commented part) in order to get it work. It seems to me that `source.videoId` is missing. Here is the modified code:

```
exports.createResolvers = ({
  actions,
  cache,
  createNodeId,
  createResolvers,
  store,
  reporter,
}) => {
  const { createNode } = actions;
  const resolvers = {
    DatoCmsVideoItem: {
      featuredImg: {
        type: `File`,
        resolve: async (source, args, context, info) => {
          return createRemoteFileNode({
            //url: source.videoId,
            url: source.entityPayload.attributes.video_id,
            createNode,
            createNodeId,
            reporter,
            cache,
            store,
          });
        },
      },
    },
  };
  createResolvers(resolvers);
};
```

Not sure if it is just me or someone also face the problem.

**Comment by matjack1** [comment] 2020-09-28 09:51
hey @winstonma could you please send me the details of your project or the particular video that you are trying to access (maybe you can send the details at support@datocms.com to check if the problem is with your project or general).

**Comment by winstonma** [comment] 2020-09-29 13:14
@matjack1 I created a fork of the [gatsby-portfolio](https://github.com/datocms/gatsby-portfolio) and added the `createResolvers` code. Here is the [diff](https://github.com/datocms/gatsby-portfolio/compare/master...winstonma:master).

Then here is the test case
1. Follow the basic procedure of [gatsby-portfolio](https://github.com/datocms/gatsby-portfolio) instruction, but of coz clone my repo instead (https://github.com/winstonma/gatsby-portfolio.git).
2. Run `yarn develop`
3. Open browser and go to GraphQL in-browser IDE (e.g. http://localhost:8000/___graphql)
4. Paste the following Query and run
```
query MyQuery {
  allDatoCmsWork {
    edges {
      node {
        title
        fullName
      }
    }
  }
}
```
Then you will see some thing print on the console. It is because `console.log(source.entityPayload.attributes.title);` print something on the console. However based on the conversation https://github.com/datocms/gatsby-source-datocms/issues/92#issuecomment-601869591, I would need `console.log(source.title);` instead.

Actually I didn't touch anything in DatoCMS and Gatsby, I just rebuild the whole project and suddenly `source.title` is gone.

**Comment by matjack1** [comment] 2020-09-29 14:10
hey @winstonma thank you, I would also need your project in Dato, could you please send that over as well?

**Comment by winstonma** [comment] 2020-09-29 14:57
@matjack1 I didn't modify the content in DatoCMS. Also the content is provided by DatoCMS.

All I did is read the content from the DatoCMS.

**Comment by matjack1** [comment] 2020-09-30 10:09
@winstonma can you please share which DatoCMS project are you using so that I can double check your records and replicate the issue?

**Comment by winstonma** [comment] 2020-09-30 10:54
@matjack1 I just leave a message to support@datocms.com

**Comment by tbrannam** [comment] 2020-10-10 19:43
Think that @winstonma is seeing a similar issue as: https://github.com/datocms/gatsby-source-datocms/issues/128

**Comment by stefanoverna** [comment] 2020-10-12 07:26
Hey, in recent versions, to achieve better loading performance, we had to make changes to how we store information inside the nodes, so yeah, the correct way now to read information is using `source.entityPayload` which returns exactly the JSON API response of our CMA with no transformations

**Comment by winstonma** [comment] 2020-10-12 08:25
Thanks Stefano. I would modify my code according to the new changes.

**Comment by winstonma** [comment] 2020-10-21 03:08
May I write down the updated code snippet in the final post so people could reference.

```
exports.createResolvers = ({
  actions,
  cache,
  createNodeId,
  createResolvers,
  store,
  reporter,
}) => {
  const { createNode } = actions;
  const resolvers = {
    DatoCmsVideoItem: {
      featuredImg: {
        type: `File`,
        resolve: async (source, args, context, info) => {
          return createRemoteFileNode({
            url: source.entityPayload.attributes.video_id,
            createNode,
            createNodeId,
            reporter,
            cache,
            store,
          });
        },
      },
    },
  };
  createResolvers(resolvers);
};
```

**Comment by PatrykRudzinski** [comment] 2021-01-13 23:36
@winstonma Your solution works well, but I've faced one problem, it fetching all images during every build, so it's looks like cache don't work. Any ideas to resolve that?

**Comment by winstonma** [comment] 2021-01-15 04:58
@PatrykRudzinski I am a free user of the datocms, I built a very small gatsby website so cache is not my priority. I guess @matjack1 would give you a perfect support.

**Comment by Js-Brecht** [comment] 2021-01-15 05:56
@PatrykRudzinski the caching done by the `gatsby-source-filesystem` is [here](https://github.com/gatsbyjs/gatsby/blob/f8bbc066767818a0713a8ea838f1d91d2ea1b6ae/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L288-L293) and [here](https://github.com/gatsbyjs/gatsby/blob/f8bbc066767818a0713a8ea838f1d91d2ea1b6ae/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L316-L343)

As you can see, when a file is received with a status of `200`, it will be stored in Gatsby's `.cache` directory (in this case, `.cache/caches/gatsby-source-filesystem`).  The headers from the file response will be stored in the node cache.

With headers cached, the next request for the same url will use `If-None-Match: "<cached etag>"`.  If the file has not changed, the server should respond with a `304`.  That means a network request is still going out, but it should not be downloading anything.  It simply moves on, storing the cached file's path on the file node in Gatsby's GraphQL layer [here](https://github.com/gatsbyjs/gatsby/blob/f8bbc066767818a0713a8ea838f1d91d2ea1b6ae/packages/gatsby-source-filesystem/src/create-remote-file-node.js#L264-L272)

**Comment by PatrykRudzinski** [comment] 2021-01-20 19:45
@winstonma thanks for quick reply. That's true, it's gatsby work to cache it. @Js-Brecht now everything is clear, thanks a lot.

**Comment by sandro768** [comment] 2021-02-11 21:33
I need to create a field in the onCreateNode API. Please reopen the issue until it's fixed.
