### ISSUE TITLE
manifest id includes characters incompatible with Azure Devops Pipelines

### ISSUE THREAD

**Issue by walpoletim** [datocms/gatsby-source-datocms#194] opened 2022-04-26 13:43 UTC
The generated Manifest ID incudes characters (.) that is incompatible with using the plugin with an Azure Develops pipeline

**Comment by stefanoverna** [comment] 2022-12-07 11:16
Sorry, but the issue is unclear... I'm gonna close this for now, but feel free to reopen if you can provide more info!

**Closed by stefanoverna** 2022-12-07 11:16 UTC
