### ISSUE TITLE
Multiple-paragraph text nodes not always available

### ISSUE THREAD

**Issue by federicobadini** [datocms/gatsby-source-datocms#54] opened 2019-05-10 13:25 UTC
Hi and thank you for the excellent work on DatoCms.

We have experienced that sometimes fields of type *Multiple-paragraph text*  are not available as nodes.

In the following query we retrieve data for a generic `Page` composed by sections.
```js
export const query = graphql`
  query pageQuery($pageId: String, $featuredProductIds: [String]) {
    datoCmsPage(id: { eq: $pageId }) {
      title
      handle
      _allBodyLocales {
        locale
        value {
          __typename
          ... on DatoCmsTitledRte {
            title
            textNode {
              childMarkdownRemark {
                html
              }
            }
          }
          # More sections
        }
      }
    }
  }
`;
```
If for any reason a particular modular section exists as a model but is not effectively used in content we have a failure of type `Unknown field 'textNode' on type 'DatoCmsTitledRte'`.

This is particularly annoying given that page modular sections are often added and removed by content editors and whenever a situation like this happens we have to modify the code.
Is it possible to add nodes to the graphql typings even in this case to avoid this situation?

**Comment by matjack1** [comment] 2019-05-13 09:36
@federicobadini you are right, I've been able to reproduce the error, we'll work on this and let you know as soon as possible

**Comment by federicobadini** [comment] 2019-05-16 09:57
Do you already have an estimated ETA?

**Comment by matjack1** [comment] 2019-05-20 10:04
@federicobadini I think either tomorrow or Wednesday we can get a fix out for this

**Comment by matjack1** [comment] 2019-05-24 10:28
hey @federicobadini I've just checked again and after having updated all the dependencies the problem is gone.

If I paste this:
```
query IndexPageQuery {
  page: datoCmsPage(originalId: {eq: "951795"}) {
    _allBodyLocales {
      locale
      value {
        ... on DatoCmsRte {
          text
          textNode {
            childMarkdownRemark{
              html
            }
          }
        }
      }
    }
  }
}
```
In my GraphiQL explorer now works fine!

Can you please confirm?

BTW, my versions:
 - node: v10.9.0
 - gatsby: v2.7.1

**Comment by matjack1** [comment] 2019-05-31 08:43
I'm going to close this for now as I fixed it by upgrading everything.

If I'm wrong feel free to reopen the issue.

**Closed by matjack1** 2019-05-31 08:43 UTC
Labels: bug
