### ISSUE TITLE
Time out Build 

### ISSUE THREAD

**Issue by Pierregadait** [datocms/gatsby-source-datocms#193] opened 2022-04-15 05:22 UTC
Hello, 

We are facing blocking issue with major business impact on our website: [https://ikeys-realty.com/en]
After reaching Gatsby support, they tell us that the **call stack error is coming from gatsby-source-datocms** which they do not maintain.

Context:
We have a timeout issue when building. Please find a screenshot of our issue : 
![unnamed](https://user-images.githubusercontent.com/101513831/163523861-84fa4129-6c02-4be8-94e0-99a1e0547996.png)

Our previous actions:
1. Verified the domain
2. Remove cloudflare proxy on all the subdomains (it was proxied for some reason)
3. Updated the IP Addresses (@ were going to an old IP on your side ?)
We also did a rebuild of the preview (there was a prompt for us to do that in gatsby). 

However, like for the previous builds, it time outed at some point (screenshot)

- We have a feeling this is happening when it's trying to regenerate the permalinks ?
- Is there a way to see whether stuff sent by Dato actually ends up in gatsby ?

Sending stuff randomly I'm seeing as marked as published from https://admin.ikeys-realty.com/ , but whose slugs are / are not working: 

[working]
1. https://ikeys-realty.com/en/19575-collins-ave-38
2. https://ikeys-realty.com/en/villa-rosetti
3. https://ikeys-realty.com/en/334-atlantic-ave

[not working]
1. https://preview-ikeys.gtsb.io/for-sale-4-bedroom-luxury-penthouse-with-panoramic-view-on-the-marina-and-the-bla
2. https://preview-ikeys.gtsb.io/epic-apartment-designed-by-the-prestigious-fendi-casa
3. https://preview-ikeys.gtsb.io/gorgeous-villa-in-algarve-in-portugal
5. https://preview-ikeys.gtsb.io/incredible-villa-in-algarve-in-portugal

FYI, the working ones, are not working in preview, so ( with and without /en/ which is also. a difference between the preview engine and the live engine ):
1. https://ikeys-realty.com/en/19575-collins-ave-38 ( doesn't work in https://preview-ikeys.gtsb.io/en/19575-collins-ave-38 )
2. https://ikeys-realty.com/en/villa-rosetti ( doesn't work in https://preview-ikeys.gtsb.io/en/villa-rosetti )
3. https://ikeys-realty.com/en/334-atlantic-ave ( doesn't work in https://preview-ikeys.gtsb.io/334-atlantic-ave )

Which makes us believe either :
1. Dato isn't sending stuff properly ( or at all ) to gatsby
5. Data gets sent, something in gatsby ( what ? ) is preventing slugs from working properly

Maybe the samples above will help you find out what's different from the working / not working permalinks?

**Comment by winstonma** [comment] 2022-04-23 04:42
First of all I am not working for DatoCMS. I also got error for my secondary locale after updating `react` and `react-dom` to v18.0.0.

@Pierregadait please set `react` and `react-dom` version to v17.0.2 and see if that works for you.

If that works then the team may get more hints on this problem.

**Comment by Pierregadait** [comment] 2022-04-23 08:40
Dear Jacques, Marcus,
Please help -

More listing in prime location around the world :
Ikeys-realty.com
 
Follow us & suscribe 
YouTube I Instagram I Facebook I LinkedIn 

Best regards, 

"iKeys, c’est tout simplement de la haute couture 
au service de l’immobilier"

Pierre-Axel Gadait
C E O / 

+ 230 5744 98 33 
________________________________

iKeys-realty.com 
Ile Maurice / Megeve / Miami / Los Angeles / Marbella / Courchevel /Saint Barth / and more luxury destination

**Comment by Pierregadait** [comment] 2022-04-23 13:37
Hi Gatsby Support,
Please note this duplicates https://support.gatsbyjs.com/hc/requests/25090

Thanks



On Sat, Apr 23, 2022 at 12:40 PM Gatsby ***@***.***> wrote:

> ##- Please type your reply above this line -##
> [image: Gatsby] <https://gatsbyjs.com/>
>
> Hi Pierre!
>
> We've received your support request *"Re: [datocms/gatsby-source-datocms]
> Time out Build (Issue #193)"*
> <https://support.gatsbyjs.com/hc/requests/25512> and will get back to you
> as soon as we can. Support hours are Monday - Friday, 8AM - 5PM US Eastern
> Time.
>
>
> To help expedite resolution, you should include the following in your
> request if you haven't already:
>
>
>    - Workspace or Site name
>    - Link to build logs
>    <https://support.gatsbyjs.com/hc/en-us/articles/360053099173-Build-Logs>
>    (for build issues)
>    - Steps to reproduce the error you are encountering
>
> You can reply to this email to share any additional details with us.
>
> If your issue is not related to Gatsby Cloud, our Gatsby Support article
> <https://support.gatsbyjs.com/hc/en-us/articles/1500012368821> recommends
> other support channels and resources that may be helpful to you.
>
>
> Thanks so much for using Gatsby!
>
>
> Sincerely,
>
>
> The Gatsby Support Engineering Team
> https://support.gatsbyjs.com/hc/requests/25512
> Status Page <https://status.gatsbyjs.com/>  |   Gatsby Cloud Help Center
> <https://support.gatsbyjs.com/>  |   Open Source Docs
> <https://www.gatsbyjs.com/docs/>  |   Submit a Feature Request
> <https://portal.gatsbyjs.com/gatsby-cloud>
>
> This email is a service from Gatsby.
> [MLY7KW-E8WE]
>

-- 
*
Please consider the environment before printing this email | Avant 
d’imprimer cet e-mail, pensez à l’environnement.*
Disclaimer: This e-mail 
message may contain confidential, proprietary or legally privileged 
information. It should not be used by anyone who is not the original 
intended recipient. Any disclosure, copying, distribution or any action 
taken or omitted to be taken in reliance on it, is prohibited and may be 
unlawful. If you have erroneously received this message, please delete it 
immediately and notify the sender. The recipient acknowledges that GWS 
Technologies LTD is unable to exercise control or ensure or guarantee the 
integrity of/over the contents of the information contained in e-mail 
transmissions and further acknowledges that any views expressed in this 
message are those of the individual sender and no binding nature of the 
message shall be implied or assumed unless the sender does so expressly 
with due authority of GWS Technologies LTD. Before opening any attachments, 
please check them for viruses and defects, since we do not accept any 
liability for loss or damage which may be caused as a result.

-- 
*
Confidential Information Sharing Policy*
Please note we do not allow 
sending of passwords and other confidential information via e-mail.
if you 
need to send us any password or other sensitive information, please paste 
it first in our private bin at https://secrets.gws-technologies.com/ 
<https://secrets.gws-technologies.com/> , and paste the generated link back 
here so the actual information doesn't get saved in our e-mail systems.

**Comment by matjack1** [comment] 2022-04-28 16:38
hey @Pierregadait I'm sorry but we are in touch with Gatsby to understand where the problem is. Unfortunately it's between us and Gatsby Cloud, so it's out of our complete control and we don't really have much clue of what's going wrong :(

We already have booked some time with Gatsby to better understand where the problem is, I hope to get you some news soon, sorry :(

**Comment by Pierregadait** [comment] 2022-04-28 18:25
Dear Matteo, 
Thank you for your reply. 
Do you have few solution for us during the period you have looking for the bug ?

Thanks in advance. 

More listing in prime location around the world :
Ikeys-realty.com
 
Follow us & suscribe 
YouTube I Instagram I Facebook I LinkedIn 

Best regards, 

"iKeys, c’est tout simplement de la haute couture 
au service de l’immobilier"

Pierre-Axel Gadait
C E O / 

+ 230 5744 98 33 
________________________________

iKeys-realty.com 
Ile Maurice / Megeve / Miami / Los Angeles / Marbella / Courchevel /Saint Barth / and more luxury destination

**Comment by Pierregadait** [comment] 2022-04-28 18:30
Matteo, 
Do you think we could insert a form between the page that opens and the page that does not open in order to at least get the contact details of the visitors and avoid that people fall on the page that does not open.
If yes, how to do it ?

More listing in prime location around the world :
Ikeys-realty.com
 
Follow us & suscribe 
YouTube I Instagram I Facebook I LinkedIn 

Best regards, 

"iKeys, c’est tout simplement de la haute couture 
au service de l’immobilier"

Pierre-Axel Gadait
C E O / 

+ 230 5744 98 33 
________________________________

iKeys-realty.com 
Ile Maurice / Megeve / Miami / Los Angeles / Marbella / Courchevel /Saint Barth / and more luxury destination

**Comment by matjack1** [comment] 2022-04-29 12:25
@Pierregadait since the build works locally it might work also in other build tools, like Netlify or Vercel maybe. So instead of building in Gatsby Cloud you can use that for preview purposes and something else for building? I think it should work fine already.

**Comment by Pierregadait** [comment] 2022-04-30 13:50
Hi Marcus,
Thank you for your reply,
Please give us news Monday of the evolution. 
Kind regards, 

More listing in prime location around the world :
Ikeys-realty.com
 
Follow us & suscribe 
YouTube I Instagram I Facebook I LinkedIn 

Best regards, 

"iKeys, c’est tout simplement de la haute couture 
au service de l’immobilier"

Pierre-Axel Gadait
C E O / 

+ 230 5744 98 33 
________________________________

iKeys-realty.com 
Ile Maurice / Megeve / Miami / Los Angeles / Marbella / Courchevel /Saint Barth / and more luxury destination

**Comment by Pierregadait** [comment] 2022-05-02 19:05
Hello Matteo,
If I give you access, could yo help me or a member of your team ?
Thank you for your reply.

Best regards,  




 <https://www.facebook.com/ikeysrealty/>	
 <https://www.linkedin.com/company/ikeys-realty/>	
 <https://www.instagram.com/ikeysrealty/>	
 <https://www.youtube.com/c/iKeysRealty>	
 	
Pierre-Axel Gadait
CEO iKeys

‭+230 5744 9833‬ <tel:%E2%80%AD+23057449833%E2%80%AC>
	***@***.*** ***@***.***>
	ikeys-realty.com <https://ikeys-realty.com/>

**Comment by Pierregadait** [comment] 2022-05-03 05:49
Hi Marcus,
Thank you,
Do you need to have access to our back office in Dato CMS ?
I think its could be great -
Let me know ?

Best regards,  




 <https://www.facebook.com/ikeysrealty/>	
 <https://www.linkedin.com/company/ikeys-realty/>	
 <https://www.instagram.com/ikeysrealty/>	
 <https://www.youtube.com/c/iKeysRealty>	
 	
Pierre-Axel Gadait
CEO iKeys

‭+230 5744 9833‬ <tel:%E2%80%AD+23057449833%E2%80%AC>
	***@***.*** ***@***.***>
	ikeys-realty.com <https://ikeys-realty.com/>

**Comment by Pierregadait** [comment] 2022-05-04 03:11
Hi Marcus,
Ok thank you. 

More listing in prime location around the world :
Ikeys-realty.com
 
Follow us & suscribe 
YouTube I Instagram I Facebook I LinkedIn 

Best regards, 

"iKeys, c’est tout simplement de la haute couture 
au service de l’immobilier"

Pierre-Axel Gadait
C E O / 

+ 230 5744 98 33 
________________________________

iKeys-realty.com 
Ile Maurice / Megeve / Miami / Los Angeles / Marbella / Courchevel /Saint Barth / and more luxury destination

**Comment by matjack1** [comment] 2022-05-04 08:25
hey @Pierregadait please try running

`yarn upgrade gatsby-source-datocms` which should in turn upgrade our JS client which has a change that should fix your issue.

Please let me know if that solves your problem!

**Comment by Pierregadait** [comment] 2022-05-05 03:47
Hello Marcus,
We receive this mail from Dato - 

"Hello Pierre,

I've also written on Github, but just to be sure, please run

yarn upgrade gatsby-source-datocms

and try again, we've fixed an underlying issue that should allow the build to work again.

Let me know if that works please.

Best

Matteo Giaccone”

Could you do the necessary in our GatsbyCloud space and try to rebuild ?

Thank you form your reply.






 <https://www.facebook.com/ikeysrealty/>	
 <https://www.linkedin.com/company/ikeys-realty/>	
 <https://www.instagram.com/ikeysrealty/>	
 <https://www.youtube.com/c/iKeysRealty>	
 	
Pierre-Axel Gadait
CEO iKeys

‭+230 5744 9833‬ <tel:%E2%80%AD+23057449833%E2%80%AC>
	***@***.*** ***@***.***>
	ikeys-realty.com <https://ikeys-realty.com/>

**Comment by matjack1** [comment] 2022-05-05 12:37
I'm going to close the issue as it's just adding confusion.

We have issued a fix for the last problem that was reported, we are going to carry on the discussion over support.

**Closed by matjack1** 2022-05-05 12:37 UTC

**Comment by Pierregadait** [comment] 2022-05-06 19:44
Dear Marcus 
Thank you, 
> When you're able, can you confirm you've made that change? It looks like recent builds for the site are failing due to running past your current memory limit, so we'll want to make sure the site is up to date before addressing that piece. 
> Yes we confirm👍🏻
> Best,

More listing in prime location around the world :
Ikeys-realty.com
 
Follow us & suscribe 
YouTube I Instagram I Facebook I LinkedIn 

Best regards, 

"iKeys, c’est tout simplement de la haute couture 
au service de l’immobilier"

Pierre-Axel Gadait
C E O / 

+ 230 5744 98 33 
________________________________

iKeys-realty.com 
Ile Maurice / Megeve / Miami / Los Angeles / Marbella / Courchevel /Saint Barth / and more luxury destination

**Comment by Pierregadait** [comment] 2022-05-07 19:54
Dear Marcus,
Here is the link of the build which failed again : https://www.gatsbyjs.com/dashboard/246e6fb0-4d2d-4117-a3e7-4f4006d82949/sites/1a5e0cb4-7ca6-49d5-b365-60132b66a409/builds/87c2ef68-629e-48aa-bf6a-246a446bcf7f/details#errors <https://www.gatsbyjs.com/dashboard/246e6fb0-4d2d-4117-a3e7-4f4006d82949/sites/1a5e0cb4-7ca6-49d5-b365-60132b66a409/builds/87c2ef68-629e-48aa-bf6a-246a446bcf7f/details#errors>

Could you upgrade to the pro plan to check if it's can work ?

Best regards,  




 <https://www.facebook.com/ikeysrealty/>	
 <https://www.linkedin.com/company/ikeys-realty/>	
 <https://www.instagram.com/ikeysrealty/>	
 <https://www.youtube.com/c/iKeysRealty>	
 	
Pierre-Axel Gadait
CEO iKeys

‭+230 5744 9833‬ <tel:%E2%80%AD+23057449833%E2%80%AC>
	***@***.*** ***@***.***>
	ikeys-realty.com <https://ikeys-realty.com/>

**Comment by Pierregadait** [comment] 2022-05-12 20:18
Dear Marcus,
It’s just been resolved 👍🏻
Thank you.
I wish you a great evening. 

Best regards, 

More listing in prime location around the world :
Ikeys-realty.com
 
Follow us & suscribe 
YouTube I Instagram I Facebook I LinkedIn 

Best regards, 

"iKeys, c’est tout simplement de la haute couture 
au service de l’immobilier"

Pierre-Axel Gadait
C E O / 

+ 230 5744 98 33 
________________________________

iKeys-realty.com 
Ile Maurice / Megeve / Miami / Los Angeles / Marbella / Courchevel /Saint Barth / and more luxury destination

**Comment by Pierregadait** [comment] 2022-10-11 08:42
Hello Marcus,
Thank you.
Have a great weekend.

More listing in prime location around the world :
Ikeys-realty.com
 
Follow us & suscribe 
YouTube I Instagram I Facebook I LinkedIn 

Best regards, 

"iKeys, c’est tout simplement de la haute couture 
au service de l’immobilier"

Pierre-Axel Gadait
C E O / 

+ 230 5744 98 33 
________________________________

iKeys-realty.com 
Ile Maurice / Megeve / Miami / Los Angeles / Marbella / Courchevel /Saint Barth / and more luxury destination
