### ISSUE TITLE
Gatsby Build fails - GraphQL Error - Modular Content Fields

### ISSUE THREAD

**Issue by drobinhood** [datocms/gatsby-source-datocms#13] opened 2018-04-25 22:59 UTC
Gatsby fails to build if there isn't a post with at least one of the modular content fields. For instance, if DatoCmsImage isn't used in a post and only DatoCmsText is used gatsby will fail with the following query. See the following build error.

```
{
  allDatoCmsBlogPost {
    edges {
      node {
        title
        content {
          ... on DatoCmsText {
            text
          }
          ... on DatoCmsImage {
            image {
              url
            }
          }
        }
      }
    }
  }
}
```

`GraphQL Error Fragment cannot be spread here as objects of type "DatoCmsText" can never be of type "DatoCmsImage".`

**Comment by AdamPflug** [comment] 2018-05-23 17:07
I believe this is essentially a duplicate of:
https://github.com/gatsbyjs/gatsby/issues/3344
https://github.com/gatsbyjs/gatsby/issues/4261

**Comment by stefanoverna** [comment] 2018-05-30 09:58
Duplicate of #14

**Closed by stefanoverna** 2018-05-30 09:58 UTC
